// InselDex – Fossilien-Daten
// 73 Fossilien aus Animal Crossing: New Horizons.
// Datenbasis: Animal Crossing Wiki / Nookipedia.
// Bilder werden NICHT mitgeliefert. Lege sie unter bilder/fossilien/ ab.
// Dateiname = id + ".png"

const fossilDaten = [
    {
        "id": "acanthostega",
        "name": "Acanthostega",
        "originalName": "Acanthostega",
        "verkaufspreis": 2000,
        "groesse": "1,0 x 1,0",
        "gruppe": "Einzelfossil",
        "mehrteilig": false,
        "teil": "",
        "bild": "bilder/fossilien/acanthostega.png"
    },
    {
        "id": "ammonit",
        "name": "Ammonit",
        "originalName": "Ammonite",
        "verkaufspreis": 1100,
        "groesse": "1,0 x 1,0",
        "gruppe": "Einzelfossil",
        "mehrteilig": false,
        "teil": "",
        "bild": "bilder/fossilien/ammonit.png"
    },
    {
        "id": "anomalocaris",
        "name": "Anomalocaris",
        "originalName": "Anomalocaris",
        "verkaufspreis": 2000,
        "groesse": "1,0 x 1,0",
        "gruppe": "Einzelfossil",
        "mehrteilig": false,
        "teil": "",
        "bild": "bilder/fossilien/anomalocaris.png"
    },
    {
        "id": "archaeopteryx",
        "name": "Archaeopteryx",
        "originalName": "Archaeopteryx",
        "verkaufspreis": 1300,
        "groesse": "1,0 x 1,0",
        "gruppe": "Einzelfossil",
        "mehrteilig": false,
        "teil": "",
        "bild": "bilder/fossilien/archaeopteryx.png"
    },
    {
        "id": "australopithecus",
        "name": "Australopithecus",
        "originalName": "Australopith",
        "verkaufspreis": 1100,
        "groesse": "1,0 x 1,0",
        "gruppe": "Einzelfossil",
        "mehrteilig": false,
        "teil": "",
        "bild": "bilder/fossilien/australopithecus.png"
    },
    {
        "id": "bernstein",
        "name": "Bernstein",
        "originalName": "Amber",
        "verkaufspreis": 1200,
        "groesse": "1,0 x 1,0",
        "gruppe": "Einzelfossil",
        "mehrteilig": false,
        "teil": "",
        "bild": "bilder/fossilien/bernstein.png"
    },
    {
        "id": "koprolith",
        "name": "Koprolith",
        "originalName": "Coprolite",
        "verkaufspreis": 1100,
        "groesse": "1,0 x 1,0",
        "gruppe": "Einzelfossil",
        "mehrteilig": false,
        "teil": "",
        "bild": "bilder/fossilien/koprolith.png"
    },
    {
        "id": "dino-fussabdruck",
        "name": "Dino-Fußabdruck",
        "originalName": "Dinosaur track",
        "verkaufspreis": 1000,
        "groesse": "1,0 x 1,0",
        "gruppe": "Einzelfossil",
        "mehrteilig": false,
        "teil": "",
        "bild": "bilder/fossilien/dino-fussabdruck.png"
    },
    {
        "id": "dunkleosteus",
        "name": "Dunkleosteus",
        "originalName": "Dunkleosteus",
        "verkaufspreis": 3500,
        "groesse": "1,0 x 1,0",
        "gruppe": "Einzelfossil",
        "mehrteilig": false,
        "teil": "",
        "bild": "bilder/fossilien/dunkleosteus.png"
    },
    {
        "id": "eusthenopteron",
        "name": "Eusthenopteron",
        "originalName": "Eusthenopteron",
        "verkaufspreis": 2000,
        "groesse": "1,0 x 1,0",
        "gruppe": "Einzelfossil",
        "mehrteilig": false,
        "teil": "",
        "bild": "bilder/fossilien/eusthenopteron.png"
    },
    {
        "id": "juramaia",
        "name": "Juramaia",
        "originalName": "Juramaia",
        "verkaufspreis": 1500,
        "groesse": "1,0 x 1,0",
        "gruppe": "Einzelfossil",
        "mehrteilig": false,
        "teil": "",
        "bild": "bilder/fossilien/juramaia.png"
    },
    {
        "id": "myllokunmingia",
        "name": "Myllokunmingia",
        "originalName": "Myllokunmingia",
        "verkaufspreis": 1500,
        "groesse": "1,0 x 1,0",
        "gruppe": "Einzelfossil",
        "mehrteilig": false,
        "teil": "",
        "bild": "bilder/fossilien/myllokunmingia.png"
    },
    {
        "id": "haizahnspirale",
        "name": "Haizahnspirale",
        "originalName": "Shark-tooth pattern",
        "verkaufspreis": 1000,
        "groesse": "1,0 x 1,0",
        "gruppe": "Einzelfossil",
        "mehrteilig": false,
        "teil": "",
        "bild": "bilder/fossilien/haizahnspirale.png"
    },
    {
        "id": "trilobit",
        "name": "Trilobit",
        "originalName": "Trilobite",
        "verkaufspreis": 1300,
        "groesse": "1,0 x 1,0",
        "gruppe": "Einzelfossil",
        "mehrteilig": false,
        "teil": "",
        "bild": "bilder/fossilien/trilobit.png"
    },
    {
        "id": "ankylosaurus-schädel",
        "name": "Ankylosaurus-Schädel",
        "originalName": "Ankylosaurus – skull",
        "verkaufspreis": 3500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Ankylosaurus",
        "mehrteilig": true,
        "teil": "schädel",
        "bild": "bilder/fossilien/ankylosaurus-schädel.png"
    },
    {
        "id": "ankylosaurus-schwanz",
        "name": "Ankylosaurus-Schwanz",
        "originalName": "Ankylosaurus – tail",
        "verkaufspreis": 2500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Ankylosaurus",
        "mehrteilig": true,
        "teil": "schwanz",
        "bild": "bilder/fossilien/ankylosaurus-schwanz.png"
    },
    {
        "id": "ankylosaurus-torso",
        "name": "Ankylosaurus-Torso",
        "originalName": "Ankylosaurus – torso",
        "verkaufspreis": 3000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Ankylosaurus",
        "mehrteilig": true,
        "teil": "torso",
        "bild": "bilder/fossilien/ankylosaurus-torso.png"
    },
    {
        "id": "archelon-hinterteil",
        "name": "Archelon-Hinterteil",
        "originalName": "Archelon – tail",
        "verkaufspreis": 3500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Archelon",
        "mehrteilig": true,
        "teil": "hinterteil",
        "bild": "bilder/fossilien/archelon-hinterteil.png"
    },
    {
        "id": "archelon-vorderteil",
        "name": "Archelon-Vorderteil",
        "originalName": "Archelon – skull",
        "verkaufspreis": 4000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Archelon",
        "mehrteilig": true,
        "teil": "vorderteil",
        "bild": "bilder/fossilien/archelon-vorderteil.png"
    },
    {
        "id": "brachiosaurus-becken",
        "name": "Brachiosaurus-Becken",
        "originalName": "Brachiosaurus – pelvis",
        "verkaufspreis": 5000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Brachiosaurus",
        "mehrteilig": true,
        "teil": "becken",
        "bild": "bilder/fossilien/brachiosaurus-becken.png"
    },
    {
        "id": "brachiosaurus-schädel",
        "name": "Brachiosaurus-Schädel",
        "originalName": "Brachiosaurus – skull",
        "verkaufspreis": 6000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Brachiosaurus",
        "mehrteilig": true,
        "teil": "schädel",
        "bild": "bilder/fossilien/brachiosaurus-schädel.png"
    },
    {
        "id": "brachiosaurus-schwanz",
        "name": "Brachiosaurus-Schwanz",
        "originalName": "Brachiosaurus – tail",
        "verkaufspreis": 5500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Brachiosaurus",
        "mehrteilig": true,
        "teil": "schwanz",
        "bild": "bilder/fossilien/brachiosaurus-schwanz.png"
    },
    {
        "id": "brachiosaurus-thorax",
        "name": "Brachiosaurus-Thorax",
        "originalName": "Brachiosaurus – chest",
        "verkaufspreis": 5500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Brachiosaurus",
        "mehrteilig": true,
        "teil": "thorax",
        "bild": "bilder/fossilien/brachiosaurus-thorax.png"
    },
    {
        "id": "deinonychus-schwanz",
        "name": "Deinonychus-Schwanz",
        "originalName": "Deinonychus – tail",
        "verkaufspreis": 2500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Deinonychus",
        "mehrteilig": true,
        "teil": "schwanz",
        "bild": "bilder/fossilien/deinonychus-schwanz.png"
    },
    {
        "id": "deinonychus-torso",
        "name": "Deinonychus-Torso",
        "originalName": "Deinonychus – torso",
        "verkaufspreis": 3000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Deinonychus",
        "mehrteilig": true,
        "teil": "torso",
        "bild": "bilder/fossilien/deinonychus-torso.png"
    },
    {
        "id": "dimetrodon-schädel",
        "name": "Dimetrodon-Schädel",
        "originalName": "Dimetrodon – skull",
        "verkaufspreis": 5500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Dimetrodon",
        "mehrteilig": true,
        "teil": "schädel",
        "bild": "bilder/fossilien/dimetrodon-schädel.png"
    },
    {
        "id": "dimetrodon-torso",
        "name": "Dimetrodon-Torso",
        "originalName": "Dimetrodon – torso",
        "verkaufspreis": 5000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Dimetrodon",
        "mehrteilig": true,
        "teil": "torso",
        "bild": "bilder/fossilien/dimetrodon-torso.png"
    },
    {
        "id": "diplodocus-becken",
        "name": "Diplodocus-Becken",
        "originalName": "Diplodocus – pelvis",
        "verkaufspreis": 4500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Diplodocus",
        "mehrteilig": true,
        "teil": "becken",
        "bild": "bilder/fossilien/diplodocus-becken.png"
    },
    {
        "id": "diplodocus-hals",
        "name": "Diplodocus-Hals",
        "originalName": "Diplodocus – neck",
        "verkaufspreis": 4500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Diplodocus",
        "mehrteilig": true,
        "teil": "hals",
        "bild": "bilder/fossilien/diplodocus-hals.png"
    },
    {
        "id": "diplodocus-schädel",
        "name": "Diplodocus-Schädel",
        "originalName": "Diplodocus – skull",
        "verkaufspreis": 5000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Diplodocus",
        "mehrteilig": true,
        "teil": "schädel",
        "bild": "bilder/fossilien/diplodocus-schädel.png"
    },
    {
        "id": "diplodocus-schwanz",
        "name": "Diplodocus-Schwanz",
        "originalName": "Diplodocus – tail",
        "verkaufspreis": 5000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Diplodocus",
        "mehrteilig": true,
        "teil": "schwanz",
        "bild": "bilder/fossilien/diplodocus-schwanz.png"
    },
    {
        "id": "diplodocus-schwanzspitze",
        "name": "Diplodocus-Schwanzspitze",
        "originalName": "Diplodocus – tail tip",
        "verkaufspreis": 4000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Diplodocus",
        "mehrteilig": true,
        "teil": "schwanzspitze",
        "bild": "bilder/fossilien/diplodocus-schwanzspitze.png"
    },
    {
        "id": "diplodocus-thorax",
        "name": "Diplodocus-Thorax",
        "originalName": "Diplodocus – chest",
        "verkaufspreis": 4000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Diplodocus",
        "mehrteilig": true,
        "teil": "thorax",
        "bild": "bilder/fossilien/diplodocus-thorax.png"
    },
    {
        "id": "iguanodon-schädel",
        "name": "Iguanodon-Schädel",
        "originalName": "Iguanodon – skull",
        "verkaufspreis": 4000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Iguanodon",
        "mehrteilig": true,
        "teil": "schädel",
        "bild": "bilder/fossilien/iguanodon-schädel.png"
    },
    {
        "id": "iguanodon-schwanz",
        "name": "Iguanodon-Schwanz",
        "originalName": "Iguanodon – tail",
        "verkaufspreis": 3000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Iguanodon",
        "mehrteilig": true,
        "teil": "schwanz",
        "bild": "bilder/fossilien/iguanodon-schwanz.png"
    },
    {
        "id": "iguanodon-torso",
        "name": "Iguanodon-Torso",
        "originalName": "Iguanodon – torso",
        "verkaufspreis": 3500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Iguanodon",
        "mehrteilig": true,
        "teil": "torso",
        "bild": "bilder/fossilien/iguanodon-torso.png"
    },
    {
        "id": "mammut-schädel",
        "name": "Mammut-Schädel",
        "originalName": "Mammut – skull",
        "verkaufspreis": 3000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Mammut",
        "mehrteilig": true,
        "teil": "schädel",
        "bild": "bilder/fossilien/mammut-schädel.png"
    },
    {
        "id": "mammut-torso",
        "name": "Mammut-Torso",
        "originalName": "Mammut – torso",
        "verkaufspreis": 2500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Mammut",
        "mehrteilig": true,
        "teil": "torso",
        "bild": "bilder/fossilien/mammut-torso.png"
    },
    {
        "id": "megacerops-schädel",
        "name": "Megacerops-Schädel",
        "originalName": "Megacerops – skull",
        "verkaufspreis": 4500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Megacerops",
        "mehrteilig": true,
        "teil": "schädel",
        "bild": "bilder/fossilien/megacerops-schädel.png"
    },
    {
        "id": "megacerops-schwanz",
        "name": "Megacerops-Schwanz",
        "originalName": "Megacerops – tail",
        "verkaufspreis": 3000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Megacerops",
        "mehrteilig": true,
        "teil": "schwanz",
        "bild": "bilder/fossilien/megacerops-schwanz.png"
    },
    {
        "id": "megacerops-torso",
        "name": "Megacerops-Torso",
        "originalName": "Megacerops – torso",
        "verkaufspreis": 3500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Megacerops",
        "mehrteilig": true,
        "teil": "torso",
        "bild": "bilder/fossilien/megacerops-torso.png"
    },
    {
        "id": "riesenhirsch-links",
        "name": "Riesenhirsch-Hälfte (L)",
        "originalName": "Riesenhirsch – Left side",
        "verkaufspreis": 4000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Riesenhirsch",
        "mehrteilig": true,
        "teil": "links",
        "bild": "bilder/fossilien/riesenhirsch-links.png"
    },
    {
        "id": "riesenhirsch-rechts",
        "name": "Riesenhirsch-Hälfte (R)",
        "originalName": "Riesenhirsch – Right side",
        "verkaufspreis": 5500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Riesenhirsch",
        "mehrteilig": true,
        "teil": "rechts",
        "bild": "bilder/fossilien/riesenhirsch-rechts.png"
    },
    {
        "id": "ophthalmosaurus-schädel",
        "name": "Ophthalmosaurus-Schädel",
        "originalName": "Ophthalmosaurus – skull",
        "verkaufspreis": 2500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Ophthalmosaurus",
        "mehrteilig": true,
        "teil": "schädel",
        "bild": "bilder/fossilien/ophthalmosaurus-schädel.png"
    },
    {
        "id": "ophthalmosaurus-torso",
        "name": "Ophthalmosaurus-Torso",
        "originalName": "Ophthalmosaurus – torso",
        "verkaufspreis": 2000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Ophthalmosaurus",
        "mehrteilig": true,
        "teil": "torso",
        "bild": "bilder/fossilien/ophthalmosaurus-torso.png"
    },
    {
        "id": "pachysaurus-hinterteil",
        "name": "Pachysaurus-Hinterteil",
        "originalName": "Pachysaurus – tail",
        "verkaufspreis": 3500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Pachysaurus",
        "mehrteilig": true,
        "teil": "hinterteil",
        "bild": "bilder/fossilien/pachysaurus-hinterteil.png"
    },
    {
        "id": "pachysaurus-vorderteil",
        "name": "Pachysaurus-Vorderteil",
        "originalName": "Pachysaurus – skull",
        "verkaufspreis": 4000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Pachysaurus",
        "mehrteilig": true,
        "teil": "vorderteil",
        "bild": "bilder/fossilien/pachysaurus-vorderteil.png"
    },
    {
        "id": "parasaurus-schädel",
        "name": "Parasaurus-Schädel",
        "originalName": "Parasaurus – skull",
        "verkaufspreis": 3500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Parasaurus",
        "mehrteilig": true,
        "teil": "schädel",
        "bild": "bilder/fossilien/parasaurus-schädel.png"
    },
    {
        "id": "parasaurus-schwanz",
        "name": "Parasaurus-Schwanz",
        "originalName": "Parasaurus – tail",
        "verkaufspreis": 2500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Parasaurus",
        "mehrteilig": true,
        "teil": "schwanz",
        "bild": "bilder/fossilien/parasaurus-schwanz.png"
    },
    {
        "id": "parasaurus-torso",
        "name": "Parasaurus-Torso",
        "originalName": "Parasaurus – torso",
        "verkaufspreis": 3000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Parasaurus",
        "mehrteilig": true,
        "teil": "torso",
        "bild": "bilder/fossilien/parasaurus-torso.png"
    },
    {
        "id": "plesiosaurus-schädel",
        "name": "Plesiosaurus-Schädel",
        "originalName": "Plesiosaurus – skull",
        "verkaufspreis": 4000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Plesiosaurus",
        "mehrteilig": true,
        "teil": "schädel",
        "bild": "bilder/fossilien/plesiosaurus-schädel.png"
    },
    {
        "id": "plesiosaurus-schwanz",
        "name": "Plesiosaurus-Schwanz",
        "originalName": "Plesiosaurus – tail",
        "verkaufspreis": 4500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Plesiosaurus",
        "mehrteilig": true,
        "teil": "schwanz",
        "bild": "bilder/fossilien/plesiosaurus-schwanz.png"
    },
    {
        "id": "plesiosaurus-torso",
        "name": "Plesiosaurus-Torso",
        "originalName": "Plesiosaurus – torso",
        "verkaufspreis": 4500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Plesiosaurus",
        "mehrteilig": true,
        "teil": "torso",
        "bild": "bilder/fossilien/plesiosaurus-torso.png"
    },
    {
        "id": "pteranodon-fluegel-l",
        "name": "Pteranodon-Flügel (L)",
        "originalName": "Pteranodon – Left wing",
        "verkaufspreis": 4500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Pteranodon",
        "mehrteilig": true,
        "teil": "fluegel-l",
        "bild": "bilder/fossilien/pteranodon-fluegel-l.png"
    },
    {
        "id": "pteranodon-fluegel-r",
        "name": "Pteranodon-Flügel (R)",
        "originalName": "Pteranodon – Right wing",
        "verkaufspreis": 4500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Pteranodon",
        "mehrteilig": true,
        "teil": "fluegel-r",
        "bild": "bilder/fossilien/pteranodon-fluegel-r.png"
    },
    {
        "id": "pteranodon-torso",
        "name": "Pteranodon-Torso",
        "originalName": "Pteranodon – torso",
        "verkaufspreis": 4000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Pteranodon",
        "mehrteilig": true,
        "teil": "torso",
        "bild": "bilder/fossilien/pteranodon-torso.png"
    },
    {
        "id": "quetzalcoatlus-fluegel-l",
        "name": "Quetzalcoatlus-Flügel (L)",
        "originalName": "Quetzalcoatlus – Left wing",
        "verkaufspreis": 5000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Quetzalcoatlus",
        "mehrteilig": true,
        "teil": "fluegel-l",
        "bild": "bilder/fossilien/quetzalcoatlus-fluegel-l.png"
    },
    {
        "id": "quetzalcoatlus-fluegel-r",
        "name": "Quetzalcoatlus-Flügel (R)",
        "originalName": "Quetzalcoatlus – Right wing",
        "verkaufspreis": 5000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Quetzalcoatlus",
        "mehrteilig": true,
        "teil": "fluegel-r",
        "bild": "bilder/fossilien/quetzalcoatlus-fluegel-r.png"
    },
    {
        "id": "quetzalcoatlus-torso",
        "name": "Quetzalcoatlus-Torso",
        "originalName": "Quetzalcoatlus – torso",
        "verkaufspreis": 4500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Quetzalcoatlus",
        "mehrteilig": true,
        "teil": "torso",
        "bild": "bilder/fossilien/quetzalcoatlus-torso.png"
    },
    {
        "id": "saebelzahn-hinterteil",
        "name": "Säbelzahn-Hinterteil",
        "originalName": "Säbelzahn – tail",
        "verkaufspreis": 2000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Säbelzahn",
        "mehrteilig": true,
        "teil": "hinterteil",
        "bild": "bilder/fossilien/saebelzahn-hinterteil.png"
    },
    {
        "id": "saebelzahn-vorderteil",
        "name": "Säbelzahn-Vorderteil",
        "originalName": "Säbelzahn – skull",
        "verkaufspreis": 2500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Säbelzahn",
        "mehrteilig": true,
        "teil": "vorderteil",
        "bild": "bilder/fossilien/saebelzahn-vorderteil.png"
    },
    {
        "id": "spinosaurus-schädel",
        "name": "Spinosaurus-Schädel",
        "originalName": "Spinosaurus – skull",
        "verkaufspreis": 4000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Spinosaurus",
        "mehrteilig": true,
        "teil": "schädel",
        "bild": "bilder/fossilien/spinosaurus-schädel.png"
    },
    {
        "id": "spinosaurus-schwanz",
        "name": "Spinosaurus-Schwanz",
        "originalName": "Spinosaurus – tail",
        "verkaufspreis": 2500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Spinosaurus",
        "mehrteilig": true,
        "teil": "schwanz",
        "bild": "bilder/fossilien/spinosaurus-schwanz.png"
    },
    {
        "id": "spinosaurus-torso",
        "name": "Spinosaurus-Torso",
        "originalName": "Spinosaurus – torso",
        "verkaufspreis": 3000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Spinosaurus",
        "mehrteilig": true,
        "teil": "torso",
        "bild": "bilder/fossilien/spinosaurus-torso.png"
    },
    {
        "id": "stegosaurus-schädel",
        "name": "Stegosaurus-Schädel",
        "originalName": "Stegosaurus – skull",
        "verkaufspreis": 5000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Stegosaurus",
        "mehrteilig": true,
        "teil": "schädel",
        "bild": "bilder/fossilien/stegosaurus-schädel.png"
    },
    {
        "id": "stegosaurus-schwanz",
        "name": "Stegosaurus-Schwanz",
        "originalName": "Stegosaurus – tail",
        "verkaufspreis": 4000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Stegosaurus",
        "mehrteilig": true,
        "teil": "schwanz",
        "bild": "bilder/fossilien/stegosaurus-schwanz.png"
    },
    {
        "id": "stegosaurus-torso",
        "name": "Stegosaurus-Torso",
        "originalName": "Stegosaurus – torso",
        "verkaufspreis": 4500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Stegosaurus",
        "mehrteilig": true,
        "teil": "torso",
        "bild": "bilder/fossilien/stegosaurus-torso.png"
    },
    {
        "id": "t-rex-schädel",
        "name": "T-Rex-Schädel",
        "originalName": "T-Rex – skull",
        "verkaufspreis": 6000,
        "groesse": "2,0 x 2,0",
        "gruppe": "T-Rex",
        "mehrteilig": true,
        "teil": "schädel",
        "bild": "bilder/fossilien/t-rex-schädel.png"
    },
    {
        "id": "t-rex-schwanz",
        "name": "T-Rex-Schwanz",
        "originalName": "T-Rex – tail",
        "verkaufspreis": 5000,
        "groesse": "2,0 x 2,0",
        "gruppe": "T-Rex",
        "mehrteilig": true,
        "teil": "schwanz",
        "bild": "bilder/fossilien/t-rex-schwanz.png"
    },
    {
        "id": "t-rex-torso",
        "name": "T-Rex-Torso",
        "originalName": "T-Rex – torso",
        "verkaufspreis": 5500,
        "groesse": "2,0 x 2,0",
        "gruppe": "T-Rex",
        "mehrteilig": true,
        "teil": "torso",
        "bild": "bilder/fossilien/t-rex-torso.png"
    },
    {
        "id": "triceratops-schädel",
        "name": "Triceratops-Schädel",
        "originalName": "Triceratops – skull",
        "verkaufspreis": 5500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Triceratops",
        "mehrteilig": true,
        "teil": "schädel",
        "bild": "bilder/fossilien/triceratops-schädel.png"
    },
    {
        "id": "triceratops-schwanz",
        "name": "Triceratops-Schwanz",
        "originalName": "Triceratops – tail",
        "verkaufspreis": 4500,
        "groesse": "2,0 x 2,0",
        "gruppe": "Triceratops",
        "mehrteilig": true,
        "teil": "schwanz",
        "bild": "bilder/fossilien/triceratops-schwanz.png"
    },
    {
        "id": "triceratops-torso",
        "name": "Triceratops-Torso",
        "originalName": "Triceratops – torso",
        "verkaufspreis": 5000,
        "groesse": "2,0 x 2,0",
        "gruppe": "Triceratops",
        "mehrteilig": true,
        "teil": "torso",
        "bild": "bilder/fossilien/triceratops-torso.png"
    }
];

const fossilMeilensteine = [
    { ab: 0,  bis: 5,  name: "Fossilienneuling" },
    { ab: 5,  bis: 10, name: "Fossilienforscher" },
    { ab: 10, bis: 20, name: "Fossilienkenner" },
    { ab: 20, bis: 30, name: "Fossilienexperte" },
    { ab: 30, bis: 40, name: "Fossiliensammler" },
    { ab: 40, bis: 73, name: "Meister der Fossilien" }
];

const fossilienGesamt = fossilDaten.length; // 73
